### ISSUE TITLE
Game Data stays blank

### ISSUE THREAD

**Issue by bope12** [kaetemi/MonsterGUI#2]
getting parse error game data stays blank so gold switched and such no longer work for me http://i.imgur.com/fl4wsjC.png

**Comment by kaetemi** [comment]
Yeah. I think something's going to shit on odd locales. I'll check why it's not doing the UTF-8 magic.

**Comment by kaetemi** [comment]
Might be fixed now.

**Comment by bope12** [comment]
Fixed
